articles/urls.py
from django.urls import path
from articles import views

app_name = 'articles'
urlpatterns = [
    path('index/', views.index),
    path('dinner/<str:name>/', views.dinner),
    path('dinner_price/', views.dinner_price, name='dinner_price'),
    path('review/', views.review, name='review'),
    path('create_review/', views.create_review, name='create_review'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
]

foods/urls.py
from django.urls import path
from foods import views

urlpatterns = [

]

project_1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('foods/', include('foods.urls')),
]

articles/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

foods/models.py
from django.db import models

# Create your models here.

articles/views.py
from django.shortcuts import render, redirect
import random
from .models import Article

# Create your views here.
def index(request):
    return render(request, 'index.html')


def dinner(request, name):
    menus = ['한식', '중식', '일식', '분식']
    pick = random.choice(menus)
    context = {
        'pick' : pick,
        'name' : name,
        'menus' : menus,
    }
    return render(request, 'dinner.html', context)


def dinner_price(request):
    menus = [{"name":'한식 정식',"price":30000}, {"name":'중식 정식',"price":20000}, {"name":'일식 정식',"price":70000}, {"name":'분식 정식',"price":8000}]
    pick = random.choice(menus)
    articles = Article.objects.all()
    context = {
        'pick' : pick,
        'menus' : menus,
        'articles'  :articles,
    }
    return render(request, 'dinner_price.html', context)


def review(request):
    return render(request, 'review.html')


def create_review(request):
    content = request.POST.get('content')
    title = request.POST.get('title')
    article = Article(title=title, content=content)
    article.save()
    
    return redirect('articles:detail', article.pk)


def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article' : article,
    }
    return render(request, 'datail.html', context)


def delete(request, pk):
    article = Article.objects.get(pk=pk)

    if request.method == 'POST':
        article.delete()
    
    return redirect('articles:dinner_price')



def edit(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article' : article,
    }
    return render(request, 'edit.html', context)


def update(request, pk):
    article = Article.objects.get(pk=pk)
    
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()
    
    return redirect('articles:detail', article.pk)

foods/views.py
from django.shortcuts import render

# Create your views here.

articles/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> 오늘의 메뉴 </title>
    <!-- CCS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body class="container">
    {% block content %} {% endblock %}
    <!-- JavaScript Bundle witn Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

articles/templates/datail.html
{% extends 'base.html' %} {% block content %}

<h2 class="text-center">DETAIL</h2>
<h3>{{ article.pk }}번 째 리뷰</h3>
<hr />
<p>글 제목 : {{ article.title }}</p>
<p>글 내용 : {{ article.content }}</p>
<p>글 작성 시간 : {{ article.created_at|date:"SHORT_DATE_FORMAT" }}</p>

<!-- a 태그는 get method로 동작하기 때문에 delete 동작은 form 태그를 통해 Post로 동작 시켜줘야 함 -->
<!-- <a href="{% url 'articles:delete' article.pk %}">[리뷰 삭제하기]</a><br /> -->

<form action="{% url 'articles:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <button class="btn btn-danger">[DELETE]</button>
</form>
<a href="{% url 'articles:edit' article.pk %}" class="btn btn-primary">[EDIT]</a><br />
<a href="{% url 'articles:dinner_price' %}">[Back]</a>
<hr />

{% endblock %}

articles/templates/dinner.html
<h1>오늘 {{name}}의 저녁은 {{pick}} 입니다!</h1>
<h1>메뉴 리스트</h1>
<ul>
    {% for menu in menus %}
    <li>{{ menu }}</li>
    {% endfor %}
</ul>

articles/templates/dinner_price.html
{% extends 'base.html' %} {% block content %}

<h1>오늘 저녁은 {{pick.name}} 입니다!</h1>
<h1>메뉴 리스트</h1>
<ul>
    {% for menu in menus %}
    <li>{{ menu.name }}{{ menu.price }}</li>
    {% endfor %}
</ul>

{% if pick.price > 20000 %}
<p>비쌈</p>
{% elif pick.price > 10000 %}
<p>먹을 수 있음</p>
{% else %}
<p>맛있겠당</p>
{% endif %}

<a href="{% url 'articles:review' %}">[리뷰 작성하기]</a>
<hr />

<h1> Review </h1>
{% for article in articles %}
<p>글 번호 : {{ article.pk }}</p>
<p>글 제목 : {{ article.title }}</p>
<p>글 내용 : {{ article.content }}</p>
<a href="{% url 'articles:detail' article.pk %}">[상세 리뷰 보기]</a>
<hr />

{% endfor %}{% endblock %}

articles/templates/edit.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center">EDIT</h1>
<form class="form-group" action="{% url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
    <label for="title"> Title : </label>
    <input class="form-control" type="text" name="title" value="{{ article.title }}"><br />
    <label for="content"> Content : </label>
    <textarea class="form-control" name="content" cols="30" rows="5">{{ article.content }}</textarea><br />
    <input type="submit" />
</form>

{% endblock %}

articles/templates/index.html
<h1> Django Templates Language </h1>

articles/templates/review.html
{% extends 'base.html' %} {% block content %}

<form 
    class="form-group"
    action="{% url 'articles:create_review' %}" 
    method="POST"
>
{% csrf_token %}
<label for="title"> Title: </label>
<input class="form-control" type="text" name="title" /><br />
<label for="content"> Content: </label>
<textarea class="form-control" name="content" cols="30" rows="5"></textarea><br />
<input type="submit" />
</form>

{% endblock %}

articles/templates/review_result.html
<h1>받은 리뷰는 {{ content }}입니다.</h1>